Update README.md
straightdave/arion pull request #3
Opened 2018-07-25 05:38 UTC by liu1700

2018-07-25 05:48 UTC, LitoMore requested changes

2018-07-25 05:48 UTC, LitoMore commented on README.md
> +try to create a temp folder in your $GOPATH/src and copy your.any.pb.go file to that folder and try again
I think this below would be better

```
Please create a temp folder in your $GOPATH/src and copy your.any.pb.go file to the temp folder then try again
```

2018-07-25 06:10 UTC, liu1700 commented on README.md
> +try to create a temp folder in your $GOPATH/src and copy your.any.pb.go file to that folder and try again
Yeah, you are right. Updated!

2018-07-25 07:13 UTC, LitoMore approved these changes

2018-07-26 16:04 UTC, straightdave commented
The solution mentioned is not accurate. Technically you can run the `arion` command everywhere to generate the postgals. The root cause of compiling error varies a lot. You can try to file an *issue* and describe how you met the problem and provide logs and error messages.

In a lot of cases I've met about compiling error they are mainly caused by:
* package conflict (you call `arion` to compile in your project folder with _vendor_ directory)
* underlying packages are not up-to-date

In the first case, you just call `arion` anywhere else, not in the projects with _vendor_ directories. For the second, you can use `-u` when running `arion` to force-update underlying packages.

2018-07-26 16:04 UTC, closed without merging

2018-07-26 16:05 UTC, straightdave commented
But thanks all the same.

2018-07-27 13:03 UTC, liu1700 commented
It might be package conflict in my case.